<a href="https://colab.research.google.com/github/ashishk121/Quantum-Hamming-distance-for-Annealer/blob/main/QUBO_formulation_quantum_hamming_distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import sympy as sp
from scipy import linalg

In [25]:
n=4;
d=int(n + pow(n,2)/2)

In [26]:
d

12

In [65]:
B=np.array([[0,1,0,1],[1,0,1,1],[0,1,0,1],[1,1,1,0]]);
I=np.identity(n);
Bsq= B.dot(B);
Bsqd=np.diagonal(Bsq)

In [ ]:
G= np.concatenate((I,B),axis=1) 

In [66]:
Bsqd

array([2, 3, 2, 3])

In [42]:
Bsq

array([[2, 1, 2, 1],
       [1, 3, 1, 2],
       [2, 1, 2, 1],
       [1, 2, 1, 3]])

In [93]:
M=np.zeros((d,d))

In [45]:
for i in range(0,n):
  print(i)

0
1
2
3


In [55]:
B[0,0]

0

In [106]:
for i in range(0,n):
  for j in range(0,n):
    if j>i:
      M[i,j]=-2*B[i,j]+ 2*Bsq[i,j]
    elif i == j:
      M[i,j]= 1+Bsqd[i]
    else:
      M[i,j]=0

for i in range(0,n):
  for j in range(n,2*n):
    M[i,j]=2*I[i,j-n]-4*B[i,j-n]

for i in range(0,n):
  for j in range(n,3*n):
    M[i,j]=2*I[i,j-2*n]-4*B[i,j-2*n]

for i in range(n,d):
  for j in range(0,d):
    if i==j:
      M[i,j]=4

for i in range(n,d):
  for j in range(0,d):
    if 
      M[i,j]=8
             

In [107]:
M

array([[ 3.,  0.,  4.,  0.,  2., -4.,  0., -4.,  2., -4.,  0., -4.],
       [ 0.,  4.,  0.,  2., -4.,  2., -4., -4., -4.,  2., -4., -4.],
       [ 0.,  0.,  3.,  0.,  0., -4.,  2., -4.,  0., -4.,  2., -4.],
       [ 0.,  0.,  0.,  4., -4., -4., -4.,  2., -4., -4., -4.,  2.],
       [ 0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.],
       [ 8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.]])

In [104]:
range(n,d)

range(4, 12)

In [105]:
range(0,d)

range(0, 12)